# Generated by Django 3.0 on 2020-01-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='posted_by',
        ),
    ]
