# Generated by Django 3.0 on 2020-01-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_user_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['pub_date']},
        ),
    ]
