# Generated by Django 2.2.4 on 2020-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20200113_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='userId',
            field=models.IntegerField(default=None),
        ),
    ]
