# Generated by Django 2.2.4 on 2020-01-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_user_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='userId',
        ),
    ]
